name: Check Tipsto Picks

on:
  schedule:
    - cron: "0 */2 * * *"   # run every 2 hours
  workflow_dispatch:        # allow manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      - name: Install SeleniumBase
        run: |
          pip install seleniumbase


      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python check_tipsto_picks.py

      - name: Commit seen list
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add seen_tipsto.txt
          git commit -m "Update seen list" || echo "No changes"
          git push
